USE sakila;

#1. List the number of films per category.
SELECT COUNT(title), name
FROM film
INNER JOIN film_category
USING (film_id)
INNER JOIN category
USING (category_id)
GROUP BY name;

#2.Retrieve the store ID, city, and country for each store.

SELECT store_id, city, country
FROM store
INNER JOIN address
USING (address_id)
INNER JOIN city
USING (city_id)
INNER JOIN country
USING (country_id);



#3 Calculate the total revenue generated by each store in dollars.

SELECT SUM(amount), store_id
FROM payment
INNER JOIN staff
USING (staff_id)
INNER JOIN store
USING (store_id)
GROUP BY (store_id);

#4. Determine the average running time of films for each category.
SELECT AVG(length), name
FROM film
INNER JOIN film_category
USING (film_id)
INNER JOIN category
USING (category_id)
GROUP BY name;


#5. Identify the film categories with the longest average running time.

SELECT AVG(length), name 
FROM film
INNER JOIN film_category
USING (film_id)
INNER JOIN category
USING (category_id)
GROUP BY name
ORDER BY AVG(length)DESC
LIMIT 3;

# 6. Display the top 10 most frequently rented movies in descending order.

SELECT title, MIN(rental_date) AS freg_rented
FROM film
INNER JOIN inventory
USING (film_id)
INNER JOIN rental
USING (inventory_id)
GROUP BY title
ORDER BY freg_rented DESC;


